name: Sphinx test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          mkdir docs
          sphinx-build -b html documents/ _build/html

      - name: Commit and push to gh-pages
        run: |-
          git config --global user.email "naic-bot@example.com"
          git config --global user.name "naic-bot"
          git checkout --orphan gh-pages
          git rm --cached -r .
          mv CNAME _build ..
          rm -rf *
          mv ../_build/* .
          mv ../CNAME .
          touch .nojekyll
          git add .
          git commit -m "generated using sphinx-build"
          git push --set-upstream origin gh-pages --force
